name: Online Pilot Academy
favicon: null
layout_spectrum: 0.5560091123916209
typography_spectrum: 0.7933518334757537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2574178781360388
  lightness: 0.42462243838235736
  saturation: 0.9979529674164951
  rhythmicContrast: 0.976161228492856
purpose: []
